#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: deploy
    gecos: deploy
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaNsxW2ZegSyvMsielOWrbZIGTzvXrqTFEUxwG99qnrAniyyOh4mv5LNuaRmmNFgwAUi+dHIWEYzht7BpTldJul58v6zXxA1IPGGYb28iO+gPESg/pyZINYzQnjrBs5hxwkiA3MmbKgIuJ80y6sZyRQlaHKK7LT99kJExeDp/frBFYNabqnk+v9vFmIRFRP6oAkvvZ+37HNdUlC7yL06i1ypWrzQe2nYRLVFso4kFjmKhcBAITjy4mxXMce7SA2xbONEOaS6PEAod1E2oYzVsT3T5isGjTLug+iV4NpvjHh22zSNqf7S4nOxV6p6EH+QmXT73R4VXnbgSmXDrQ8CtFU8cHd8EUfdvt20V3sMEIfKwAaaxO1COO+U+VRmt4hZ/xpo+ftzVTgbc7KM0CZsXYM5ACYCV7RC+8jHY3/3c/5fyZFBiHfY259ue/hr9iBJ25ZwNh285wJF0qen8Brmp558+mgOtFaSP+Rd5vs9HJuIppUoNzMQBzcXOJVgfjfwGGoYPx/jkUorjIPC2j6JzE7nJBZHuBS3YKDwEkSiO10iKHT2i6A3sxKgelKApk8Gq7v2BABm5AwV1RZ5VyU1Bk6pcNchfAo7qZfC45mGyDZ/8bagN+isgZzg2VnXUnB/RABgXxGiOAEs8/1oQqOedb6YbTv/uqAmAYFND0j3aXiw== Maxence CROSSE@AsusByMcarre

# Downloads the python package
packages:
  - python3

# Sets the GOPATH & downloads the demo payload
runcmd:
